.ALIASES
R_R6            R6(1=0 2=OUT )
R_R3            R3(1=N01612 2=N01610 )
R_R4            R4(1=OUT 2=N01258 )
V_V5            V5(+=IN -=0 )
Q_Q1            Q1(c=N01612 b=IN e=N01258 )
R_R5            R5(1=0 2=OUT )
R_R2            R2(1=IN 2=N00897 )
V_V3            V3(+=N00897 -=0 )
R_R1            R1(1=0 2=IN )
V_V4            V4(+=N01610 -=0 )
_    _(out=OUT)
_    _(IN=IN)
.ENDALIASES
